export {
  Service,
  TipoServico,
  StatusServico,
  StatusCronograma,
  StatusPagamento,
  TipoDocumento,
  CategoriaCusto,
  FormaPagamento,
  type ClienteInfo,
  type CronogramaItem,
  type PagamentoItem,
  type DocumentoItem,
  type CustoFixoItem,
  type ParcelamentoItem,
  type ServiceStats,
} from '@manager/domain'
